### PR TITLE
Update dependencies.

### PR DESCRIPTION
**Pull request by JakeWharton**

### CODE REVIEW

**Comment by artem-zinnatullin** [comment]
You can declare dependencies better, as Map in `ext`:

In root `build.gradle`
```groovy
ext.libraries = [
  rxJava: 'io.reactivex:rxjava:1.0.11',
  mockito: 'org.mockito:mockito-core:1.10.19'
]
```

In submodule:

```groovy
dependencies {
  compile libraries.rxJava
}
```

See http://stackoverflow.com/questions/9547170/in-gradle-how-do-i-declare-common-dependencies-in-a-single-place/9547593#9547593

**Comment by JakeWharton** [comment]
This is the `ext` map.

**Comment by artem-zinnatullin** [comment]
Yep, but in submodules:
 `compile libraries.rxJava` 

looks better than:
 `compile rootProject.ext.rxJava` :)

**Comment by JakeWharton** [comment]
Yeah I've done that in some other projects but considering there's no behavior change I'm not going to spend time going around changing everything just to save a few characters on a reference that rarely changes.

**Comment by artem-zinnatullin** [comment]
No problem, just wanted to share nice solution.

**Pull request merged**
